.github/pull_request_template.md
- Closes issue: N/A
- Create a pull request template to be used to give more context for reviewers, note if there are any breaking changes and to provide a place to add in images etc of the new changes for preview
- None
Preview of the pull request - its giving inception vibes!
=> Add: pull request template

README.md
=> Add basic structure to README

README.md
- Closes issue: NA
Added in some blank lines to the README to facilitate team members reviewing and merging their first pull request
- None
None
=> refactor: add blank lines for PR practice

404.html, README.md, assets/css/404.css
- Closes issue: #22 
- Create 404 page and css file for 404 page
- Meta tags added to the page - these will be completed in a separate issue
- Color scheme to be finalised, colors used are placeholders
- Will need to add header/footer or button to return to homepage to allow users to navigate away from the 404 page
- None
=> Add 404 page (PR for Krishan)

README.md
=> Add content to design section of README

404.html, README.md, assets/css/404.css, assets/css/style.css, index.html
- Closes issue: #9 
- Created navbar and added to 404 page and index.html
- Added meta tags to the index page
- Refactored index page to order stylesheets correctly, moved scripts to bottom of file and add in comments
- Updated style.css to use variables for colour palette
- Add favicon to 404 page
- Add starter content to responsiveness and tech used sections of README
- None
Screenshot shows navbar with hover effect on nav links
=> Add Navbar, Styling and Refactoring

index.html
This change reverts a deletion of a section on the home page that was removed in error
- None
- None
=> revert: add back in section removed in error

index.html
=> Update the branDes branch

README.md
My first PR! 😊
Added a Features section to the README.
=> Added a Features section to the README.

assets/css/style.css, index.html
=> Added a glowing border and bg image to the home page

404.html, darth-quiz.html, index.html, wiki.html
Update some of the meta tags - just the responsive image to be done now once taken
Added the about page href to all navs
Updated navbar href's in quiz
None
None
=> Update Meta Tags & Navbar href's

assets/js/quiz.js
You can ignore my empty commits.
Hid the start and next buttons when the user clicks start on the quiz.
=> Krishan's quiz update -Hid the start and next buttons.

about.html, assets/js/script.js, index.html
- Add back in the meta tags to the home page 
- Remove extra function that wasn't required in script.js and remove commented out code
- Uncomment the footer on the about page
- 
None
None
=> Update index page meta tags & fix issue with sound effects

assets/css/wiki.css, assets/js/quiz.js, quiz.html
1. Issue was that there were two DIVS with the same id. You should use a class here instead of id, but I just added a new
id as a quick fix.
2. Fixes navbar on Wikpage.
- Closes issue: #66
- Closes Issues:#49
=> add welcome-text-2 id, hide when the quiz starts

assets/css/style.css
=> highlight quiz answer on mouse over, fit div to width of content

assets/css/style.css, assets/js/quiz.js, quiz.html
=> Hide restart button

assets/css/wiki.css, wiki.html
- Add content to WIki timeline
- Add padding to CSS so that bottom accordion can be seen when opened
None
None
=> Add content to timeline and fix bug with padding-bottom

about.html, assets/css/about.css, assets/css/style.css, index.html
- Resize .logo-card
- Correct the link to the font-family in style.css
- Make the font-size responsive to diferent screen sizes
- Add logo-card to About us page
- CONFLICT (content): Merge conflict in wiki.html
error: could not apply ff5b9bf... Add .logo-card to wiki and quiz page
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".-  Canceled the last commit, in otder not to create unwanted conflicts
=> Resize Logo card, make the Font sizes responsive and add Logo card to About us page

assets/js/quiz.js
=> Fix incorrect answers in quiz

assets/css/about.css, assets/css/style.css, index.html
- Edit logo card to take full screen
- Add new text to homepage cards
- Make text responsive for medium size screen
- 
- 
=> Make the .logo-card take the full width of the screen in index html

assets/css/style.css, assets/js/quiz.js
=> fix hide restart button

assets/js/quiz.js
=> Fix navbar toggle icon on quiz page

assets/css/style.css
=> Fix Starwars font URL

assets/css/wiki.css, wiki.html
=> wiki background image

about.html, assets/css/about.css, assets/css/style.css, assets/js/script.js, index.html
… text reveals into same function call to fix sound problem
=> Fixed sound not playing in home page issue... hoepfully!

README.md
=> Add to features and intro of README

assets/css/style.css, quiz.html
❗ IMPORTANT - You can ignore this commit [updated quiz.html with w3 validation updates.](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/commit/8af348aacfb16aacf52842cbf431ca974c494ad1)❗️
=> Krishan - Quiz image update and Burger menu styles

about.html
- Add aria labels to teh about us page
=> Add aria-labels to the GitHub and LinkedIn links in the AboutUs page

about.html, index.html, wiki.html
- ![Error_index html](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/152976651/2980079b-436b-4b6c-9de5-889c10179020)
=> Replace the spaces in audio names with %20

assets/css/style.css, index.html, quiz.html
Reverts DesislavaNaydenova/2405-hackathon-team1-StarWars#112
=> Revert "Windu"

quiz.html
added score-message id to trigger the scoreboard
=> added score-message id to trigger the scoreboard

quiz.html
=> commented out jquery

about.html, assets/css/wiki.css, wiki.html
=> add wiki instructions

README.md, assets/css/about.css
=> Add missing } in about.css, add credit for image in README
